CREATE TABLE Core.[DimUsers]
(
	[Id] INT NOT NULL IDENTITY(1,1),
	Source_Name Varchar(20),
	Batch_Id int,
	Created_Time datetimeoffset,
	Updated_Time datetimeoffset,
	Current_Flag varchar(1),
	Delete_Flag varchar(1),
	UserId int,
	Username varchar(50),
	Password varchar(500),
	UserVerifyType tinyint,
	UserType tinyint,
	UserStatus int,
	UserCreatedTime Datetimeoffset,
	AuthDevice_DeviceId varchar(100),
	AuthDevice_PublicKey varchar(1000),
	AuthDevice_SecureData varchar(max),
	AuthDevice_ActiveTime Datetimeoffset,
	Profile_AccountName varchar(50),
	Profile_Mobile varchar(30),
	Profile_FullName nvarchar(100),
	Profile_Email varchar(30),
	Profile_Passport varchar(30),
	Profile_Avatar varchar(150),
	Profile_Attributes nvarchar(max),
	ProfileVerification_ImageUrl varchar(1000),
	ProfileVerification_VerifyStatus tinyint,
	ProfileVerification_Description nvarchar(200),
	ProfileVerification_UserConfirm varchar(50),
	ProfileVerification_ConfirmTime Datetimeoffset,
	ProfileVerification_CreatedTime Datetimeoffset,
	SercureConfig_SecureType int,
	SercureConfig_MinAmount Numeric(28,12),
	SercureConfig_SecureStatus tinyint,
	SercureConfig_NotifyType varchar(20),
	SercureConfig_ModifiedTime Datetimeoffset,
	UsersAuth_UserName varchar(50),
	UsersAuth_IsVerify bit,
	UsersAuth_CreatedTime Datetimeoffset
)
