CREATE TABLE Core.[FactTransactionsReceipt]
(
	[Id] INT NOT NULL IDENTITY(1,1),
	Source_Name Varchar(20),
	Batch_Id int,
	Sync_Id int,
	Created_Time datetimeoffset,
	Updated_Time datetimeoffset,
	Current_Flag varchar(1),
	Delete_Flag varchar(1),
	TransactionId bigint,
	SourceReceiptId bigint,
	PayType tinyint,
	UserId int,
	AccountId int,
	AccountName varchar(50),
	BankAccount varchar(30),
	BankCode varchar(30),
	Amount numeric(28,12),
	Fee numeric(28,12),
	RelatedFee numeric(28,12),
	RelatedAmount numeric(28,12),
	RelatedUserId int,
	RelatedAccountId int,
	RelatedAccount varchar(50),
	Description nvarchar(300),
	PaymentApp varchar(50),
	PaymentReferenceId varchar(50),
	BankReferenceId varchar(50),
	BillingOrderId bigint,
	CreatedUser varchar(50),
	DeviceType tinyint,
	ClientIP varchar(50),
	ReceiptCreatedTime datetimeoffset,
	ReceiptInitTime datetimeoffset
)
